
source /System/Pipline/DNA/DNA_Micro/16S_pipeline/16S_pipeline_V1.10/lib/03.OTU/lib/biom_activate.sh

pick_closed_reference_otus.py -i /Disk04/Project/Micro/liyanli/liufan/03.Make_OTU/otu97/all_rep_set.fasta -r /System/Pipline/DNA/DNA_Micro/16S_pipeline/16S_pipeline_V1.10/software/picrust/picrust-1.0.0/picrust/data/gg_13_5_otus/rep_set/97_otus.fasta -o OTUs
/home/hongzhifan/bin/python/HC/Predict_fun/config/otu_comb.py -i /Disk04/Project/Micro/liyanli/liufan/03.Make_OTU/otu97/otu_table.even.txt -r OTUs/uclust_ref_picked_otus/all_rep_set_otus.txt -o otu_table.even.ref.txt

#Predict_metagenomes
unset PYTHONPATH
export PYTHONPATH=/System/Pipline/DNA/DNA_Micro/16S_pipeline/16S_pipeline_V1.10/software/picrust/Python-2.7.8/lib/python2.7/site-packages:$PYTHONPATH
biom convert -i otu_table.even.ref.txt -o otu_table.even.ref.biom  --table-type="OTU table"


normalize_by_copy_number.py -i otu_table.even.ref.biom -o otu_table.even.ref.norm.biom
predict_metagenomes.py -f -t ko -i otu_table.even.ref.norm.biom -o otu_table.even.metagenome_predictions.ko.tab
predict_metagenomes.py -t ko -i otu_table.even.ref.norm.biom -o otu_table.even.metagenome_predictions.ko.biom

#Function_categorize
mkdir Function_categorize
mv otu_table.even.metagenome_predictions.ko.* Function_categorize/
cd Function_categorize/
/home/hongzhifan/bin/python/HC/Predict_fun/config/convert_percent.py -i otu_table.even.metagenome_predictions.ko.tab

categorize_by_function.py -i otu_table.even.metagenome_predictions.ko.biom -c KEGG_Pathways -l 1 -o otu_table.even.metagenome_predictions.L1.tab -f
categorize_by_function.py -i otu_table.even.metagenome_predictions.ko.biom -c KEGG_Pathways -l 1 -o otu_table.even.metagenome_predictions.L1.biom
/home/hongzhifan/bin/python/HC/Predict_fun/config/convert_percent.py -i otu_table.even.metagenome_predictions.L1.tab

categorize_by_function.py -i otu_table.even.metagenome_predictions.ko.biom -c KEGG_Pathways -l 2 -o otu_table.even.metagenome_predictions.L2.tab -f
categorize_by_function.py -i otu_table.even.metagenome_predictions.ko.biom -c KEGG_Pathways -l 2 -o otu_table.even.metagenome_predictions.L2.biom
/home/hongzhifan/bin/python/HC/Predict_fun/config/convert_percent.py -i otu_table.even.metagenome_predictions.L2.tab

categorize_by_function.py -i otu_table.even.metagenome_predictions.ko.biom -c KEGG_Pathways -l 3 -o otu_table.even.metagenome_predictions.L3.tab -f
categorize_by_function.py -i otu_table.even.metagenome_predictions.ko.biom -c KEGG_Pathways -l 3 -o otu_table.even.metagenome_predictions.L3.biom
/home/hongzhifan/bin/python/HC/Predict_fun/config/convert_percent.py -i otu_table.even.metagenome_predictions.L3.tab

#************************************************************************** I AM A LONLY LINE **************************************************************************
#CorrelationAnalysis
cd /Disk04/Project/Micro/liyanli/liufan/function/CorrelationAnalysis
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.ko.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/CorrelationAnalysis/pick.perc.ko.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L1.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/CorrelationAnalysis/pick.perc.L1.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L2.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/CorrelationAnalysis/pick.perc.L2.tab

/home/hongzhifan/bin/python/HC/Predict_fun/config/FunctionAndBactericalCorrelationAnalysis.pl -intab /Disk04/Project/Micro/liyanli/liufan/function/CorrelationAnalysis/pick.perc.ko.tab -alpha_d /Disk04/Project/Micro/liyanli/liufan/03.Make_OTU/otu97/../../04.Diversity/Alpha_Diversity/alpha_diversity97.txt -group /Disk04/Project/Micro/liyanli/liufan/function/CorrelationAnalysis/group

#************************************************************************** I AM A LONLY LINE **************************************************************************
#PCA
cd /Disk04/Project/Micro/liyanli/liufan/function/PCA
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.ko.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/PCA/pick.perc.ko.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L1.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/PCA/pick.perc.L1.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L2.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/PCA/pick.perc.L2.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L3.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/PCA/pick.perc.L3.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/pca_check.py /Disk04/Project/Micro/liyanli/liufan/function/PCA/pick.perc.L3.tab
#Levelk
/System/Pipline/DNA/DNA_Micro/16S_pipeline/16S_pipeline_V1.10/lib/04.Diversity/lib/PCA/PCA.R.group.pl /Disk04/Project/Micro/liyanli/liufan/function/PCA/pick.perc.ko.tab /Disk04/Project/Micro/liyanli/liufan/function/PCA/group 0.2 /Disk04/Project/Micro/liyanli/liufan/function/PCA/levelk 2>/Disk04/Project/Micro/liyanli/liufan/function/PCA/levelk/pca.log
#Level1
/System/Pipline/DNA/DNA_Micro/16S_pipeline/16S_pipeline_V1.10/lib/04.Diversity/lib/PCA/PCA.R.group.pl /Disk04/Project/Micro/liyanli/liufan/function/PCA/pick.perc.L1.tab /Disk04/Project/Micro/liyanli/liufan/function/PCA/group 0.2 /Disk04/Project/Micro/liyanli/liufan/function/PCA/level1 2>/Disk04/Project/Micro/liyanli/liufan/function/PCA/level1/pca.log
#Level2
/System/Pipline/DNA/DNA_Micro/16S_pipeline/16S_pipeline_V1.10/lib/04.Diversity/lib/PCA/PCA.R.group.pl /Disk04/Project/Micro/liyanli/liufan/function/PCA/pick.perc.L2.tab /Disk04/Project/Micro/liyanli/liufan/function/PCA/group 0.2 /Disk04/Project/Micro/liyanli/liufan/function/PCA/level2 2>/Disk04/Project/Micro/liyanli/liufan/function/PCA/level2/pca.log
#Level3
/System/Pipline/DNA/DNA_Micro/16S_pipeline/16S_pipeline_V1.10/lib/04.Diversity/lib/PCA/PCA.R.group.pl /Disk04/Project/Micro/liyanli/liufan/function/PCA/check.table.xls /Disk04/Project/Micro/liyanli/liufan/function/PCA/group 0.2 /Disk04/Project/Micro/liyanli/liufan/function/PCA/level3 2>/Disk04/Project/Micro/liyanli/liufan/function/PCA/level3/pca.log

#************************************************************************** I AM A LONLY LINE **************************************************************************
#Bar
cd /Disk04/Project/Micro/liyanli/liufan/function/Bar
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.ko.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/Bar/pick.perc.ko.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L1.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/Bar/pick.perc.L1.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L2.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/Bar/pick.perc.L2.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L3.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/Bar/pick.perc.L3.tab
#Level1
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/04.Function/lib/KEGG/bin/get_table_head2.pl /Disk04/Project/Micro/liyanli/liufan/function/Bar/pick.perc.L1.tab 35 -trantab > /Disk04/Project/Micro/liyanli/liufan/function/Bar/level1/level1.relative.tran.35.xls
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/00.Commbin/top10/bar_diagram.pl -right -grid -rotate='-45' -x_title 'Sample Name' -y_title 'Relative Abundance' --y_mun 0.25,4 --height 350 -table /Disk04/Project/Micro/liyanli/liufan/function/Bar/level1/level1.relative.tran.35.xls > /Disk04/Project/Micro/liyanli/liufan/function/Bar/level1/level1.bar.svg
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Bar/level1/level1.bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Bar/level1/level1.bar.pdf
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Bar/level1/level1.bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Bar/level1/level1.bar.png
#Level2
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/04.Function/lib/KEGG/bin/get_table_head2.pl /Disk04/Project/Micro/liyanli/liufan/function/Bar/pick.perc.L2.tab 35 -trantab > /Disk04/Project/Micro/liyanli/liufan/function/Bar/level2/level2.relative.tran.35.xls
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/00.Commbin/top10/bar_diagram.pl -right -grid -rotate='-45' -x_title 'Sample Name' -y_title 'Relative Abundance' --y_mun 0.25,4 --height 350 -table /Disk04/Project/Micro/liyanli/liufan/function/Bar/level2/level2.relative.tran.35.xls > /Disk04/Project/Micro/liyanli/liufan/function/Bar/level2/level2.bar.svg
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Bar/level2/level2.bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Bar/level2/level2.bar.pdf
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Bar/level2/level2.bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Bar/level2/level2.bar.png
#Level3
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/04.Function/lib/KEGG/bin/get_table_head2.pl /Disk04/Project/Micro/liyanli/liufan/function/Bar/pick.perc.L3.tab 35 -trantab > /Disk04/Project/Micro/liyanli/liufan/function/Bar/level3/level3.relative.tran.35.xls
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/00.Commbin/top10/bar_diagram.pl -right -grid -rotate='-45' -x_title 'Sample Name' -y_title 'Relative Abundance' --y_mun 0.25,4 --height 350 -table /Disk04/Project/Micro/liyanli/liufan/function/Bar/level3/level3.relative.tran.35.xls > /Disk04/Project/Micro/liyanli/liufan/function/Bar/level3/level3.bar.svg
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Bar/level3/level3.bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Bar/level3/level3.bar.pdf
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Bar/level3/level3.bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Bar/level3/level3.bar.png
#************************************************************************** I AM A LONLY LINE **************************************************************************
#Tree_bar
cd /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.ko.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/pick.perc.ko.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L1.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/pick.perc.L1.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L2.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/pick.perc.L2.tab
/home/hongzhifan/bin/python/HC/Predict_fun/config/sample_pick.py -i /Disk04/Project/Micro/liyanli/liufan/function/Function_categorize/percent.otu_table.even.metagenome_predictions.L3.tab -s 'HFXLeaf.03 HFXLeaf.04 HFXLeaf.09 HFXShoot.03 HFXShoot.04 HFXShoot.09 HFXSoil.03 HFXSoil.04 HFXSoil.09 HFXWater.03 HFXWater.04 HFXWater.09 HXYLeaf.01 HXYLeaf.08 HXYLeaf.09 HXYShoot.01 HXYShoot.08 HXYShoot.09 HXYSoil.01 HXYSoil.08 HXYSoil.09 HXYWater.01 HXYWater.09 LFXLeaf.04 LFXLeaf.12 LFXLeaf.14 LFXShoot.04 LFXShoot.12 LFXShoot.14 LFXSoil.04 LFXSoil.12 LFXSoil.14 LFXWater.04 LFXWater.12 LFXWater.14 LXYLeaf.06 LXYLeaf.10 LXYLeaf.12 LXYShoot.06 LXYShoot.10 LXYShoot.12 LXYSoil.06 LXYSoil.10 LXYSoil.12 LXYWater.06 LXYWater.10 LXYWater.12' -o /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/pick.perc.L3.tab
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/00.Commbin/cluster/cluster.pl -BC -Z -x /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/pick.perc.L1.tab > level1.relative.tree
#Level1
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/04.Function/lib/KEGG/bin/get_table_head2.pl /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/pick.perc.L1.tab 35 -trantab > /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level1/level1.relative.tran.35.xls
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/00.Commbin/cluster/draw_tree.pl -bun 0.25,4 -bline -type 4 level1.relative.tree /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level1/level1.relative.tran.35.xls --flank_x 100 > /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level1/level1.Tree_bar.svg
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level1/level1.Tree_bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level1/level1.Tree_bar.pdf
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level1/level1.Tree_bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level1/level1.Tree_bar.png
#Level2
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/04.Function/lib/KEGG/bin/get_table_head2.pl /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/pick.perc.L2.tab 35 -trantab > /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level2/level2.relative.tran.35.xls
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/00.Commbin/cluster/draw_tree.pl -bun 0.25,4 -bline -type 4 level1.relative.tree /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level2/level2.relative.tran.35.xls --flank_x 100 > /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level2/level2.Tree_bar.svg
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level2/level2.Tree_bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level2/level2.Tree_bar.pdf
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level2/level2.Tree_bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level2/level2.Tree_bar.png
#Level3
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/04.Function/lib/KEGG/bin/get_table_head2.pl /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/pick.perc.L3.tab 35 -trantab > /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level3/level3.relative.tran.35.xls
/System/Pipline/DNA/DNA_Micro/MetaGenome_pipeline/MetaGenome_pipeline_V2.2/lib/00.Commbin/cluster/draw_tree.pl -bun 0.25,4 -bline -type 4 level1.relative.tree /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level3/level3.relative.tran.35.xls --flank_x 100 > /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level3/level3.Tree_bar.svg
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level3/level3.Tree_bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level3/level3.Tree_bar.pdf
/usr/bin/convert -density 300 /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level3/level3.Tree_bar.svg /Disk04/Project/Micro/liyanli/liufan/function/Tree_bar/level3/level3.Tree_bar.png
#************************************************************************** I AM A LONLY LINE *************************************************************
